export enum ResponseMessages {
    SUCCESS = 'SUCCESS',
    BAD_REQUEST = 'BAD_REQUEST',
    UNAUTHORIZED = 'UNAUTHORIZED',
    FORBIDDEN = 'FORBIDDEN',
    NOT_FOUND = 'NOT_FOUND',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    BAD_GATEWAY = 'BAD_GATEWAY',

    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    PHONE_ALREADY_EXISTS = 'PHONE_ALREADY_EXISTS',
}
